data_dir: "/data/baryal/HKH_new/processed_new"
run_name: "b_temp"
normalize: "mean-std"
class_name: 
  clean_ice: 1
  debris: 2
batch_size: 64
use_channels: [0,1,2,3,4,5,6,7,8,9]
loss_opts:
  name: "ce"
  masked: True
  weights: [0.1, 0.5, 1.5]
  label_smoothing: 0.1
model_opts:
  args: 
    inchannels: 10
    outchannels: 3
    net_depth: 3
    dropout: 0.2
    spatial: True
    first_channel_output: 64
optim_opts:
  name: "Adam"
  args:
    lr: 0.0001
iou_threshold: True