data_dir: "/data/baryal/HKH/processed_L08_2015"
gpu_rank: 0
run_name: "2_l08"
normalize: "mean-std"
class_name: 
  clean_ice: 1
  debris: 2
batch_size: 32
use_channels: [0,1,2,3,4,5,6,7,8,9,10]
loss_opts:
  name: "dice"
  masked: True
  weights: [1,1,1]
  label_smoothing: 0.1
model_opts:
  args: 
    inchannels: 11
    outchannels: 3
    net_depth: 4
    dropout: 0.2
    spatial: True
    first_channel_output: 32
optim_opts:
  name: "Adam"
  args:
    lr: 0.0001
iou_threshold: True