data_dir: "/data/baryal/HKH"
normalize: "mean-std"
gpu_rank: 0
folder_name: "runs"
run_name: "4_top_19"
cleanice_processed_dir: "processed_L07_2005_cleanice"
debris_processed_dir: "processed_L07_2005_debris"
out_processed_dir: "processed_L07_2005"
threshold: [0.5, 0.5]
model_opts_cleanice:
  args:
    inchannels: 19
    outchannels: 2
    net_depth: 4
    dropout: 0.00000001
    spatial: True
    first_channel_output: 32
model_opts_debris:
  args:
    inchannels: 19
    outchannels: 2
    net_depth: 4
    dropout: 0.00000001
    spatial: True
    first_channel_output: 32
optim_opts:
  name: "Adam"
  args:
    lr: 0.001
use_channels_cleanice: [18, 7, 6, 5, 16, 4, 3, 10, 15, 19, 0, 9, 14, 11, 17, 8, 1, 2, 13]
use_channels_debris: [14, 6, 5, 9, 10, 18, 7, 11, 4, 15, 19, 8, 16, 3, 17, 2, 1, 0, 12]