data_dir: "/Users/baryal/Downloads/kelp"
gpu_rank: 1
class_name: ["Kelp"]
threshold: [0.9, 0.1]
batch_size: 8
run_name: "dice"
epochs: 251
save_every: None
use_channels: [0, 1, 2, 3, 4]
normalize: "mean-std"
loss_opts:
  name: "dice"
  masked: True
  weights: [1, 0]
  gaussian_blur_sigma: None
  label_smoothing: 0.1
  alpha: 0.9
model_opts:
  args:
    inchannels: 5
    outchannels: 2
    net_depth: 4
    dropout: 0.1
    spatial: True
    first_channel_output: 8
optim_opts:
  name: "Adam"
  args:
    lr: 0.005
log_opts:
  mask_names: ["Kelp", "Background"]
metrics_opts: ["IoU", "precision", "recall"]
fine_tune: False
comment: "rgb"
find_lr: False
