data_dir: "/data/baryal/HKH/processed_L07_2005_cleanice"
gpu_rank: 0
class_name: ["Clean Ice"]
threshold: [0.5, 0.5]
batch_size: 8
run_name: "5_l07_sea_rsi"
epochs: 581
save_every: None
use_channels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
normalize: "mean-std"
loss_opts:
  name: "dice"
  masked: True
  weights: [1.0, 1.0]
  gaussian_blur_sigma: 2
  label_smoothing: 0
model_opts:
  args:
    inchannels: 14
    outchannels: 2
    net_depth: 4
    dropout: 0.2
    spatial: True
    first_channel_output: 32
optim_opts:
  name: "Adam"
  args:
    lr: 0.001
log_opts:
  mask_names: ["Background", "Clean Ice"]
metrics_opts: ["IoU", "precision", "recall"]
fine_tune: False
comment: "SEA + RSI Image"
find_lr: False
