data_dir: "/data/baryal/HKH_new"
run_name: 'weighted'
processed_dir: 'processed'
window_size: [512, 512]
threshold: [0.11, 0.99]
model_opts:
  args: 
    inchannels: 13
    outchannels: 3
    net_depth: 3
    dropout: 0.2
    spatial: True
    first_channel_output: 64
optim_opts:
  name: "Adam"
  args:
    lr: 0.001
reg_opts:
  l1_reg: 0.0005
add_ndvi: True
add_ndwi: True
add_ndsi: True
use_channels: [0,1,2,3,4,5,6,7,8,9,10,11,12]