data_dir: "/data/baryal/HKH_new/processed"
class_name: ["Clean Ice", "Debris Covered"]
batch_size: 4
run_name: "a_ce"
epochs: 101
save_every: None
use_channels: [0,1,2,3,4,5,6,7,8,9,10,11,12]
loss_opts:
  name: "dice"
  masked: True
  weights: [0.02, 0.11, 1.1]
  label_smoothing: 0.1
model_opts:
  args: 
    inchannels: 13
    outchannels: 3
    net_depth: 5
    dropout: 0.2
    spatial: True
    first_channel_output: 64
optim_opts:
  name: "Adam"
  args:
    lr: 0.002
log_opts:
  mask_names: ["Background", "Clean Ice", "Debris Covered"]
metrics_opts: ["IoU", "precision", "recall"]
grad_accumulation_steps: None
fine_tune: False
reg_opts:
  l1_reg: 0.0001
comment: "bigger model, cyclic LR, GELU"
find_lr: False