data_dir: "/data/baryal/HKH/processed_L07_2005_debris"
gpu_rank: 1
class_name: ["Debris"]
threshold: [0.5, 0.5]
batch_size: 8
run_name: "4_top_1"
epochs: 251
save_every: None
use_channels: [14]
normalize: "mean-std"
loss_opts:
  name: "custom"
  masked: True
  weights: [1.0]
  gaussian_blur_sigma: None
  label_smoothing: 0.1
  alpha: 0.1
model_opts:
  args:
    inchannels: 1
    outchannels: 2
    net_depth: 4
    dropout: 0.1
    spatial: True
    first_channel_output: 32
optim_opts:
  name: "Adam"
  args:
    lr: 0.0003
log_opts:
  mask_names: ["Background", "Debris"]
metrics_opts: ["IoU", "precision", "recall"]
fine_tune: False
comment: "L07"
find_lr: False
