data_dir: "/data/baryal/HKH_new/processed_new"
class_name: ["Clean Ice", "Debris Covered"]
threshold: [0.35, 0.99]
batch_size: 8
run_name: "f_16_inchannels"
epochs: 151
save_every: None
use_channels: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
normalize: "mean-std"
loss_opts:
  name: "dice"
  masked: True
  weights: [0.05, 0.12, 0.89]
  label_smoothing: 0.1
model_opts:
  args: 
    inchannels: 16
    outchannels: 3
    net_depth: 3
    dropout: 0.2
    spatial: True
    first_channel_output: 64
optim_opts:
  name: "Adam"
  args:
    lr: 0.0001
log_opts:
  mask_names: ["Background", "Clean Ice", "Debris Covered"]
metrics_opts: ["IoU", "precision", "recall"]
grad_accumulation_steps: None
fine_tune: False
reg_opts:
  l1_reg: 0.0001
comment: "dice loss, cyclic LR, GELU"
find_lr: False