data_dir: "/datadrive/original_fx_res_1.0_v3/"
class_name: "Fornix"
batch_size: 8
run_name: "b_dice_unaugmented"
epochs: 101
save_every: None
use_channels: [0,1,2]
loss_opts:
  name: "dice"
  masked: True
  weights: [0.1, 0.9]
  label_smoothing: 0.1
model_opts:
  args: 
    inchannels: 3
    outchannels: 2
    net_depth: 4
    dropout: 0.2
    spatial: True
    first_channel_output: 32
optim_opts:
  name: "Adam"
  args:
    lr: 0.0001
log_opts:
  mask_names: ["Greymatter", "Fornix"]
metrics_opts: ["IoU", "precision", "recall"]
grad_accumulation_steps: None
fine_tune: False
reg_opts:
  l1_reg: 0.00001