data_dir: "/data/baryal/HKH"
normalize: "mean-std"
gpu_rank: 0
folder_name: "runs"
run_name: "5_l07_sea_rsi"
cleanice_processed_dir: "processed_L07_2005_cleanice"
debris_processed_dir: "processed_L07_2005_debris"
out_processed_dir: "processed_L07_2005"
threshold: [0.5, 0.5]
model_opts:
  args:
    inchannels: 14
    outchannels: 2
    net_depth: 4
    dropout: 0.00000001
    spatial: True
    first_channel_output: 32
optim_opts:
  name: "Adam"
  args:
    lr: 0.001
use_channels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
