data_dir: "/data/baryal/HKH"
normalize: "mean-std"
gpu_rank: 0
folder_name: "runs"
run_name: "3_l07_se"
processed_dir: "processed_L07_2005"
threshold: [0.21, 0.95]
model_opts:
  args:
    inchannels: 10
    outchannels: 3
    net_depth: 4
    dropout: 0.00000001
    spatial: True
    first_channel_output: 32
optim_opts:
  name: "Adam"
  args:
    lr: 0.001
reg_opts:
  l1_reg: 0.0001
use_channels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
